### ISSUE TITLE
401 Unauthorized while getting product count

### ISSUE THREAD

**Issue by KaIKuxy** [AcrylicShrimp/dlsite-downloader#1]
This issue started happening several hours ago, seems like dlsite had some server side change.

```
{'status': 401, 'message': 'Unauthorized'}
Traceback (most recent call last):
  File "...\dlsite-downloader-devel\src\main.py", line 59, in <module>
    count = res['user']
KeyError: 'user'
```

**Comment by AcrylicShrimp** [comment]
Thanks for reporting! Let me check, I will update authentication logic if it has changes.

**Comment by KaIKuxy** [comment]
You can repro it in a normal browser. 
1. `https://login.dlsite.com/login`
2. Go to `https://www.dlsite.com/maniax`
3. You will find that it's not logged in.

I've found a workaround, I can make another request to www.dlsite.com/maniax/login/=/skip_register/1

```
res = s.get('https://www.dlsite.com/maniax/login/=/skip_register/1', allow_redirects=True)
```

But it shouldn't be the right way to fix it :)

```
# Send a authentication request with the XSRF-TOKEN. NOTE: We have to follow the redirect.
res = s.post('https://login.dlsite.com/login', data={
    'login_id': settings['username'],
    'password': settings['password'],
    '_token': s.cookies['XSRF-TOKEN']
}, allow_redirects=True)

// Seems like only after making this request will you be able to set correct login status in dlsite.com
res = s.get('https://www.dlsite.com/maniax/login/=/skip_register/1', allow_redirects=True)
```

**Comment by AcrylicShrimp** [comment]
Ok, I found the the DLsite is responding 302 to make users get redirected to `https://login.dlsite.com/guide/welcome` for some reason when user hits `https://login.dlsite.com/login`. I could reproduce this on normal browser. But I cannot now, my browser is not getting redirected anymore.

**Comment by AcrylicShrimp** [comment]
The URL you mentioned was the key. We have to make a request to `https://www.dlsite.com/maniax/login/=/skip_register/1` to prevent these server actions. I don't know why, but I works.

```python
s = requests.Session()

# Skip account guidance which blocks all authentication requests.
s.get('https://www.dlsite.com/maniax/login/=/skip_register/1')

# Get a XSRF-TOKEN by sending a get request. The XSRF-TOKEN is in the response cookie.
s.get('https://login.dlsite.com/login')

# Send a authentication request with the XSRF-TOKEN. NOTE: We have to follow redirects.
res = s.post('https://login.dlsite.com/login', data={
    'login_id': settings['username'],
    'password': settings['password'],
    '_token': s.cookies['XSRF-TOKEN']
}, allow_redirects=True)

# Get the product count.
res = s.get('https://play.dlsite.com/api/product_count').json()
```

Let me update and publish a new release.

**Comment by KaIKuxy** [comment]
Just to mention another interesting thing, I failed to log out -> log in yesterday on all of my devices until I cleaned up my cookies. Really curious about what is happening on the server-side.

**Comment by AcrylicShrimp** [comment]
That's interesting. I published a new release which fixes this issue.

https://github.com/AcrylicShrimp/dlsite-downloader/releases/tag/v1.3.0

But I cannot use Windows machine currently, so it will take some time(1 ~ 2 days) to release for Windows as well. Please close this issue when you think it is fixed.

Again, thank you for reporting this!

**Comment by AcrylicShrimp** [comment]
I added a Windows version as well. Sorry for late.

**Comment by AcrylicShrimp** [comment]
Can we close this issue now?
